# Generated by Django 4.0.6 on 2022-08-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=2, help_text='위도', max_digits=500)),
                ('longitude', models.DecimalField(decimal_places=2, help_text='경도', max_digits=500)),
                ('gender', models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
