# Generated by Django 4.0.6 on 2022-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0002_remove_toilet_childtoiletnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='경도', max_digits=500, null=True),
        ),
    ]
